export const CONTEXT_MENU_ICONS = {
  cut: 'scissors',
  copy: 'copy',
  paste: 'clipboard',
  pasteSpecial: 'clipboard-check',
  pasteValues: 'file-text',
  pasteFormat: 'paintbrush',
  insert: 'plus',
  rowAbove: 'rows-3',
  rowBelow: 'rows-3',
  colLeft: 'columns-3',
  colRight: 'columns-3',
  delete: 'trash-2',
  clear: 'eraser',
  clearAll: 'eraser',
  clearContents: 'file-x',
  clearFormats: 'sparkles',
  freeze: 'snowflake',
  unfreeze: 'slash',
  sortAsc: 'arrow-down-a-z',
  sortDesc: 'arrow-up-z-a',
  filter: 'filter',
  link: 'link',
  chart: 'chart-bar',
  chevronRight: 'chevron-right',
} as const;
