#!/usr/bin/env node
/**
 * pin-fonts.mjs — download all Google Fonts used by the apps into the
 * shared @office/fonts package (packages/fonts) and generate a local
 * @font-face stylesheet, removing the CDN @import.
 *
 * Usage: node scripts/pin-fonts.mjs
 * Reads the @import url(...) from apps/docs/src/assets/styles/styles.css,
 * fetches the CSS2 response (Chrome UA → woff2), downloads every distinct
 * font file, and writes packages/fonts/src/fonts.css + files under
 * packages/fonts/src/fonts/.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const STYLES_CSS = join(ROOT, 'apps/docs/src/assets/styles/styles.css');
const FONTS_DIR = join(ROOT, 'packages/fonts/src/fonts');
const OUT_CSS = join(ROOT, 'packages/fonts/src/fonts.css');
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

/** Nguồn danh sách font khi styles.css không còn @import Google Fonts (đã tự host). */
const DEFAULT_FONTS_URL =
  'https://fonts.googleapis.com/css2?family=Arvo:wght@400;700&family=Bangers&family=Caveat:wght@400;700&family=Cinzel:wght@400;700&family=Courier+Prime:wght@400;700&family=Dancing+Script:wght@400;700&family=EB+Garamond:wght@400;700&family=Great+Vibes&family=Inconsolata:wght@400;700&family=JetBrains+Mono:wght@400;700&family=Lato:wght@400;700&family=Lobster&family=Lora:wght@400;700&family=Merriweather:wght@400;700&family=Montserrat:wght@400;700&family=Noto+Sans:wght@400;700&family=Noto+Serif:wght@400;700&family=Nunito:wght@400;700&family=Open+Sans:wght@400;700&family=Oswald:wght@400;700&family=Pacifico&family=Permanent+Marker&family=Playfair+Display:wght@400;700&family=Poppins:wght@400;700&family=Raleway:wght@400;700&family=Roboto:wght@400;500;700&family=Roboto+Mono:wght@400;700&family=Rye&family=Satisfy&family=Share+Tech+Mono&family=Shadows+Into+Light&family=Source+Sans+3:wght@400;700&family=Special+Elite&family=Ubuntu:wght@400;700&family=Ubuntu+Mono:wght@400;700&family=Vollkorn:wght@400;700&display=swap';

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const fetchWithRetry = async (url, retries = 3) => {
  for (let attempt = 1; attempt <= retries; attempt += 1) {
    try {
      const res = await fetch(url, { headers: { 'User-Agent': UA } });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return res;
    } catch (err) {
      if (attempt === retries) throw err;
      await sleep(400 * attempt);
    }
  }
  throw new Error('unreachable');
};

/** Parse a CSS2 response into { subset, family, weight, style, unicodeRange, srcUrl }[]. */
const parseFaces = (css) => {
  const faces = [];
  let subset = 'latin';
  let idx = 0;
  while (idx < css.length) {
    const comment = css.indexOf('/*', idx);
    const face = css.indexOf('@font-face', idx);
    if (comment === -1 && face === -1) break;

    if (face !== -1 && (comment === -1 || face < comment)) {
      const end = css.indexOf('}', face);
      if (end === -1) break;
      const block = css.slice(face, end + 1);
      const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
      const weight = block.match(/font-weight:\s*([^;]+);/)?.[1]?.trim();
      const style = block.match(/font-style:\s*(\w+)/)?.[1] ?? 'normal';
      const unicodeRange = block.match(/unicode-range:\s*([^;]+);/)?.[1];
      const srcUrl = block.match(/url\(([^)]+)\)/)?.[1];
      if (family && weight && srcUrl) {
        faces.push({ subset, family, weight, style, unicodeRange, srcUrl });
      }
      idx = end + 1;
      continue;
    }

    const end = css.indexOf('*/', comment);
    if (end === -1) break;
    subset = css.slice(comment + 2, end).trim();
    idx = end + 2;
  }
  return faces;
};

const main = async () => {
  const css = readFileSync(STYLES_CSS, 'utf8');
  const importMatch = css.match(/@import url\('([^']+fonts\.googleapis\.com[^']+)'\)/);
  const importUrl = importMatch ? importMatch[1] : DEFAULT_FONTS_URL;
  if (!importMatch) console.log('[pin-fonts] no CDN @import found — using DEFAULT_FONTS_URL');
  console.log(`[pin-fonts] fetching ${importUrl}`);

  const res = await fetchWithRetry(importUrl);
  const remoteCss = await res.text();
  const faces = parseFaces(remoteCss);
  console.log(`[pin-fonts] ${faces.length} @font-face blocks`);

  mkdirSync(FONTS_DIR, { recursive: true });

  const outLines = ['/* Generated by scripts/pin-fonts.mjs — do not edit by hand. */'];
  const urlToFileMap = new Map();

  for (const face of faces) {
    let file = urlToFileMap.get(face.srcUrl);

    if (!file) {
      const safeFamily = face.family.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      const safeWeight = face.weight.replace(/[^a-z0-9]+/g, '-');
      file = `${safeFamily}-${safeWeight}-${face.style}-${face.subset}.woff2`;
      const target = join(FONTS_DIR, file);

      if (!existsSync(target)) {
        process.stdout.write(`[pin-fonts] downloading ${file} ... `);
        try {
          const fileRes = await fetchWithRetry(face.srcUrl);
          const buf = Buffer.from(await fileRes.arrayBuffer());
          writeFileSync(target, buf);
          console.log(`${(buf.length / 1024).toFixed(1)} KB`);
        } catch (err) {
          console.error(`FAILED ${face.srcUrl} (${err.message})`);
          process.exitCode = 1;
          continue;
        }
      }
      urlToFileMap.set(face.srcUrl, file);
    }

    outLines.push(`@font-face {`);
    outLines.push(`  font-family: '${face.family}';`);
    outLines.push(`  font-style: ${face.style};`);
    outLines.push(`  font-weight: ${face.weight};`);
    outLines.push(`  font-display: swap;`);
    outLines.push(`  src: url('./fonts/${file}') format('woff2');`);
    if (face.unicodeRange) outLines.push(`  unicode-range: ${face.unicodeRange};`);
    outLines.push(`}`);
    outLines.push('');
  }

  writeFileSync(OUT_CSS, outLines.join('\n'));
  console.log(
    `[pin-fonts] wrote ${OUT_CSS} (${faces.length} faces, ${urlToFileMap.size} unique font files)`,
  );
};

main().catch((err) => {
  console.error('[pin-fonts]', err);
  process.exit(1);
});
